// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOR.Data.EFs;

namespace SOR.Data.Migrations
{
    [DbContext(typeof(SORDbContext))]
    [Migration("20220418104924_Intal")]
    partial class Intal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SOR.Data.Entitis.Agencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumberPhone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Office")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("SOR.Data.Entitis.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<string>("HistoryOperation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("Operation")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TimeOperation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.ToTable("Historys");
                });

            modelBuilder.Entity("SOR.Data.Entitis.NewsLabel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.ToTable("NewsLabel");
                });

            modelBuilder.Entity("SOR.Data.Entitis.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSolve")
                        .HasColumnType("datetime");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("IsStatus")
                        .HasColumnType("int");

                    b.Property<string>("LocationReport")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LocationUser")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NewsLabelId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAngel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("NewsLabelId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("SOR.Data.Entitis.ReportProof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Proof")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportProof");
                });

            modelBuilder.Entity("SOR.Data.Entitis.ReportResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.ToTable("ReportResult");
                });

            modelBuilder.Entity("SOR.Data.Entitis.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("IsState")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.ToTable("State");
                });

            modelBuilder.Entity("SOR.Data.Entitis.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgenciesId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndLogin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FistLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IPCreate")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Identification")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PassWord")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TimeDelete")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciesId")
                        .IsUnique()
                        .HasFilter("[AgenciesId] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.History", b =>
                {
                    b.HasOne("SOR.Data.Entitis.User", "User")
                        .WithMany("Histories")
                        .HasForeignKey("CreateUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.NewsLabel", b =>
                {
                    b.HasOne("SOR.Data.Entitis.User", "User")
                        .WithMany("NewsLabels")
                        .HasForeignKey("CreateUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.Report", b =>
                {
                    b.HasOne("SOR.Data.Entitis.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("CreateUser");

                    b.HasOne("SOR.Data.Entitis.NewsLabel", "NewsLabel")
                        .WithMany("Reports")
                        .HasForeignKey("NewsLabelId");

                    b.Navigation("NewsLabel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.ReportProof", b =>
                {
                    b.HasOne("SOR.Data.Entitis.User", "User")
                        .WithMany("ReportProofs")
                        .HasForeignKey("CreateUser");

                    b.HasOne("SOR.Data.Entitis.Report", "Report")
                        .WithMany("ReportProofs")
                        .HasForeignKey("ReportId");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.ReportResult", b =>
                {
                    b.HasOne("SOR.Data.Entitis.User", "User")
                        .WithMany("ReportResults")
                        .HasForeignKey("CreateUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.State", b =>
                {
                    b.HasOne("SOR.Data.Entitis.User", "User")
                        .WithMany("State")
                        .HasForeignKey("CreateUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.User", b =>
                {
                    b.HasOne("SOR.Data.Entitis.Agencies", null)
                        .WithOne("User")
                        .HasForeignKey("SOR.Data.Entitis.User", "AgenciesId");
                });

            modelBuilder.Entity("SOR.Data.Entitis.Agencies", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("SOR.Data.Entitis.NewsLabel", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SOR.Data.Entitis.Report", b =>
                {
                    b.Navigation("ReportProofs");
                });

            modelBuilder.Entity("SOR.Data.Entitis.User", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("NewsLabels");

                    b.Navigation("ReportProofs");

                    b.Navigation("ReportResults");

                    b.Navigation("Reports");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
